name: GlguysWrath
main: com.gmail.emertens.glguyswrath.GlguysWrath
version: 1.0
author: glguy

permissions:
  glguyswrath.bypass:
    default: op
    description: bypass wrath restrictions
  glguyswrath.createcurse:
    default: op
    description: Able to create special items
  glguyswrath.creategem:
    default: op
    description: Able to create flight gems
  glguyswrath.setflightrespawn:
    default: op
    description: Able to set the flight gem respawn block
  glguyswrath.findgem:
    default: true
    description: Allow the use of /findgem

commands:
  curseitem:
     permission: glguyswrath.createcurse
     description: Curse the held item
     usage: /<command>
  flightgem:
     permission: glguyswrath.creategem
     description: Create a flight gem
     usage: /<command>
  setflightgemrespawn:
     permission: glguyswrath.setflightrespawn
     description: Set the respawn block for the flight gem
     usage: /<command>
  findgem:
     permission: glguyswrath.findgem
     description: Point compass at gem location
     usage: /<command>
