name: FlightGem
main: com.gmail.emertens.flightgem.FlightGemPlugin
version: 1.6
author: glguy
softdepend: [Essentials]

permissions:
  flightgem.bypass:
    default: op
    description: Bypass gem storage restrictions
  flightgem.creategem:
    default: op
    description: Able to create new flight gems
  flightgem.setflightrespawn:
    default: op
    description: Able to set the flight gem respawn block
  flightgem.findgem:
    default: true
    description: Able to use /findgem

commands:
  flightgem:
     permission: flightgem.creategem
     description: Create a flight gem
     usage: /<command>
  setflightgemrespawn:
     permission: flightgem.setflightrespawn
     description: Set the respawn block for the flight gem
     usage: /<command>
  findgem:
     permission: flightgem.findgem
     description: Point compass at gem location
     usage: /<command>
